version: '3.8'

services:
  kitchen-sink-front:
    image: kitchen-sink-front:latest # Specify the desired image name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: kitchen-sink-front