name: Build and deploy Angular app to Azure Web App - kitchensink-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Show contents of dist folder (debug)
        run: ls -R dist

      - name: Zip build output
        run: |
          cd dist/kitchen-sink-front
          zip -r ../../release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8A17F08894664E11AD354E4041FABE1B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C3E1E4597BEB42FE8EE38D8E52181415 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0B854A00D3374432BFDD8FA2746114E3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kitchensink-frontend'
          slot-name: 'Production'
          package: .